steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ["ci"]
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ["install", "--no-save", "firebase-tools"]
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ["run", "build"]
  - name: node:$_NODE_VERSION
    entrypoint: "./node_modules/.bin/firebase"
    args:
      [
        "target:apply",
        "--project",
        "$PROJECT_ID",
        "--token",
        "$_TOKEN",
        "hosting",
        "$BRANCH_NAME",
        "$_SITE_ID",
      ]
  - name: "node"
    entrypoint: "./node_modules/.bin/firebase"
    args:
      [
        "deploy",
        "--project",
        "$PROJECT_ID",
        "--token",
        "$_TOKEN",
        "--only",
        "hosting:$BRANCH_NAME",
      ]
